module.exports = {
  SET_RECORDS: "SET_RECORDS",
  GET_ALL_RECORDS: "GET_ALL_RECORDS",
  ADD_RECORD: "ADD_RECORD",
  CREATE_RECORD: "CREATE_RECORD",
  UPDATE_RECORD: "UPDATE_RECORD",
  DELETE_RECORD: "DELETE_RECORD"
};
